add xstream
online-ml/river pull request #1126
Opened 2022-12-26 09:58 UTC by Sophie-Normand

We are currently working to implement PySAD into River, for the "polytechnique-project".
It is a pull request for adding the method "xstream".

Sophie Normand

2022-12-26 12:15 UTC, MaxHalford requested changes
Hey there! Thanks for issuing this PR, as xStream is a valuable algorithm to add.

There are quite some changes to do for this to be accepted in the codebase. I've made a few comments in a first pass. The main issue really is that you're using numpy, whereas we mostly try to avoid numpy in River. Ideally you should reimplement the logic with pure Python. 

PS: Have you installed the `pre-commit` hooks as documented in `CONTRIBUTING.md`? Those should help you catch a lot of code style issues

2022-12-26 12:15 UTC, MaxHalford commented on river/utils/math.py
> +    iterator = ArrayStreamer(shuffle=False)
Do you use this function? I don't see where `ArrayStreamer` is imported

2022-12-26 12:15 UTC, MaxHalford commented on river/utils/math.py
> -
Your code editor is removing empty lines, but it shouldn't be. They increase readibility

2022-12-26 12:15 UTC, MaxHalford commented on river/utils/math.py
> +    A -= Au @ np.linalg.inv(eye + V @ Au) @ V @ A
Your code editor shouldn't remove the last empty line of a file

2022-12-26 12:15 UTC, MaxHalford commented on river/anomaly/base_transformer.py
> +class BaseTransformer(ABC):
What does this class do differently than the existing `Transformer` class in the `base` module? Do you really need to introduce a new base class?

2022-12-26 12:15 UTC, MaxHalford commented on river/anomaly/xstream.py
> +        window_size (int): The size (and the sliding length) of the reference window (Default=25).
As you can see in the rest of River's codebase, we don't use this format for documenting class parameters.

2022-12-26 12:15 UTC, MaxHalford commented on river/anomaly/xstream.py
> +class _Chain:
Can you say what this class does? It's a bit difficult to understand from just looking at the code

2023-01-09 10:20 UTC, MaxHalford commented
@Sophie-Normand is it ok if I close this PR?

2023-01-09 10:47 UTC, Sophie-Normand commented
> 

Yes, sure. You can close this PR

2023-01-09 11:18 UTC, closed without merging